# Generated by Django 6.0.4 on 2026-04-25 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Green Valley Apartment, Unit 4B', max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(default='', help_text='e.g. Manhattan, Gulshan, or Downtown', max_length=100)),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Total rent for the apartment', max_digits=10)),
                ('total_rooms', models.IntegerField(default=1)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_apartments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='apartments.apartment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resident Record',
                'verbose_name_plural': 'Resident Records',
                'unique_together': {('resident', 'apartment', 'is_active')},
            },
        ),
    ]
